export const GET_ME_SUCCESS = 'GET_ME_SUCCESS'
export const GET_ME_LOADING = 'GET_ME_LOADING'
export const GET_ME_FAILED = 'GET_ME_FAILED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_LOADING = 'SIGNUP_LOADING'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

export const GET_CRUD_SUCCESS = 'GET_CRUD_SUCCESS'
export const GET_CRUD_LOADING = 'GET_CRUD_LOADING'
export const GET_CRUD_FAILED = 'GET_CRUD_FAILED'

export const CREATE_CRUD_SUCCESS = 'CREATE_CRUD_SUCCESS'
export const CREATE_CRUD_LOADING = 'CREATE_CRUD_LOADING'
export const CREATE_CRUD_FAILED = 'CREATE_CRUD_FAILED'

export const EDIT_CRUD_SUCCESS = 'EDIT_CRUD_SUCCESS'
export const EDIT_CRUD_LOADING = 'EDIT_CRUD_LOADING'
export const EDIT_CRUD_FAILED = 'EDIT_CRUD_FAILED'

export const DELETE_CRUD_SUCCESS = 'DELETE_CRUD_SUCCESS'
export const DELETE_CRUD_LOADING = 'DELETE_CRUD_LOADING'
export const DELETE_CRUD_FAILED = 'DELETE_CRUD_FAILED'
